### ISSUE TITLE
MonitorManager fire interface 

### ISSUE THREAD

**Issue by juanjoarce7456** [airabinovich/java_petri_engine#3]
Fire interface should admit a String as parameter and internally get the transition that corresponds with that String. I have to be unable to access a specific transition from outside the Petri Engine (I think I am already).

**Comment by airabinovich** [comment]
That string has to be the friendly name given to the transition by the petri developer

**Comment by airabinovich** [comment]
Why should you be unable to access a transition from outside the engine?
