### ISSUE TITLE
SPIKE: wrap fire outcome inside state or strategy pattern

### ISSUE THREAD

**Issue by juanjoarce7456** [airabinovich/java_petri_engine#41]
Analize and if needed, implement a refactor of PetriMonitor.internalFireTransition method

This is to avoid throwing exceptions from PetriNet.fire(Transition) anda catching them.

Analize if state or strategy patterns can handle this issue.
The basic idea is returning (or setting somehow) an object that knows how to handle a specific condition instead of handling it in a catch block.

__Outcome of this spike__:
- Implementation (if result if satisfactory)
- Documentation of problem and solution

**Comment by airabinovich** [comment]
This spike didn't have a successful outcome. The related issue was fixed in another way.
Documentation pending

**Comment by airabinovich** [comment]
Documentation in project report
