### ISSUE TITLE
MonitorManager should accept perennial firing on transitions

### ISSUE THREAD

**Issue by juanjoarce7456** [airabinovich/java_petri_engine#5]
Monitor Manager should accept perennial firing on transitions.
Given fired transition t0 is enabled.
When thread th0 fires transition t0 using perennial firing.
Then petri monitor shall not try to sleep th0.
And petri monitor should try to wake a thread from transition t0's queue.

**Comment by airabinovich** [comment]
TODO: define if all transition should tolerate perennial firing or if this is another label and it becomes a transition's property.

In case perennial firing is a transition's property, firing interface should not change but return value should always be true for perennial transitions

EDIT:
All transitions can be fired using perennial firing.
Perennial fire returns true always, even if the transition wasn't actually fired

**Comment by airabinovich** [comment]
Should perennial firing a timed transition send the thread to sleep on its own?

EDIT:
Yes, it makes sense. If not, you would have to wait outside the monitor for the timespan to occur and that doesn't make sense
